### ISSUE TITLE
给常用菜单的 button 添加 data-id 属性

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12518]
- app\src\menus\
- app\src\mobile\menu

---

- [x] 如果选项隐藏了（display:none），按上下方向键时就跳过 https://github.com/siyuan-note/siyuan/commit/4300a353b455f4e3f898b5f14a58e05e38e4b356
- [x] 块标菜单
	- [x] 块标菜单大部分选项 #12525
	- [x] 块标菜单的 `转换为` 子菜单 https://github.com/siyuan-note/siyuan/commit/d21b122429a5ac36a6a07c9584584fc70b11bba9 #12559
- [x] `/` 菜单（.hint--menu） #12547
- [x] 文档菜单
	- [x] 文档标题旁的块菜单（data-name="titleMenu"）及其子菜单、文档树右键菜单（右键笔记本/右键文档/多选文档后右键） #12608
	- [x] .protyle-breadcrumb 上的"更多"菜单（data-name="breadcrumbMore"） #12644
- [x] 页签右键菜单 #12645
- [x] 窗口左上角的主菜单 #12648
- [x] 某些类型的块/元素的右键菜单
	- [x] 图片右键菜单 https://github.com/siyuan-note/siyuan/pull/14182
- [x] 搜索结果右键菜单里的 `复制为` 子菜单 https://github.com/siyuan-note/siyuan/pull/14182
- [x] 数据库菜单
	- [x] 属性菜单的字段菜单 https://github.com/siyuan-note/siyuan/pull/14182
	- [x] 字段菜单 https://github.com/siyuan-note/siyuan/pull/14182
	- [x] 视图菜单 https://github.com/siyuan-note/siyuan/pull/14182
	- [x] 条目右键菜单 https://github.com/siyuan-note/siyuan/pull/14182
- [ ] 其他菜单……

> 与 #12506 配合

---

1. 用户能简单地用 CSS 代码片段隐藏不需要显示的特定选项，避免写 JS 监听和修改 DOM 影响性能。
2. 社区开发者可以通过 data-id 属性定位到菜单中的特定选项，针对性开发功能。

![image](https://github.com/user-attachments/assets/a145359b-5406-48d9-a87c-804b07fbe5b0)

> p.s. #8524 感觉遥遥无期

> 关联需求 https://github.com/siyuan-note/siyuan/issues/9166#issuecomment-2132198644

**Comment by 88250** [comment]
欢迎 PR。

**Comment by TCOTC** [comment]
OK，在研究了。另外我有个问题，

width 比 height 多一个 `type: "readonly",` ，但是 DOM 好像没啥区别，为啥？

![image](https://github.com/user-attachments/assets/d320c51d-8e38-4fcc-b9d6-425c6cb4293d)

![image](https://github.com/user-attachments/assets/40977648-bce5-40d3-8828-1477fce3848c)

**Comment by TCOTC** [comment]
@Vanessa219 这几个 `id: "assetSubMenu",` 有什么特殊作用吗？能改吗？

![image](https://github.com/user-attachments/assets/d96be12a-0ffa-4923-897d-8cf81238b615)

**Comment by Vanessa219** [comment]
主要区别为事件，具体可参见 https://github.com/siyuan-note/siyuan/blob/cd40ec50bbebe87ba6de7bf832805a73ffd5c476/app/src/menus/Menu.ts

用于 https://github.com/siyuan-note/siyuan/blob/3ba4eb755f1e4303590ad8fbc84d087be0ee6da8/app/src/protyle/hint/index.ts#L829

**Comment by TCOTC** [comment]
> 没搞明白 `id: "assetSubMenu",` 有啥用，换掉好像也没影响，等学了 JS 和 TS 以后再看看

**Comment by zxkmm** [comment]
这个没有什么用处，用css隐藏了条目用键盘上下键移动焦点还是会被选中，造成更多困扰。

**Comment by TCOTC** [comment]
@Vanessa219 思源有没有办法处理一下，如果选项隐藏了（display:none），按上下方向键时就跳过

**Comment by Vanessa219** [comment]
使用 class `fn__none`

这些情况下需要显示子菜单
![QQ_1726804253662](https://github.com/user-attachments/assets/65a1d20a-6a63-4fa2-b1e2-4b731c9555e3)

**Comment by TCOTC** [comment]
> 使用 class `fn__none`

我粗略试了一下好像不行？而且无法通过 CSS 实现

[视频.webm](https://github.com/user-attachments/assets/fd235a62-ee69-4fd5-8c3b-aa691d43ebc4)

**Comment by Vanessa219** [comment]
是哦，代码已提交。

**Comment by TCOTC** [comment]
经过测试，在 #12525 使用以下 CSS 代码片段可以隐藏菜单，并且按方向键会跳过高度为 0 的选项。

```css
.b3-menu__item[data-id="ai"] {
    display: none;
}
```

**Comment by TCOTC** [comment]
子菜单该怎样添加 data-id ？我不懂怎么改

**Comment by Vanessa219** [comment]
一样的，参照 

![QQ_1726976177008](https://github.com/user-attachments/assets/d145ade2-4922-4ff1-a335-234e13bcf578)

![QQ_1726976193983](https://github.com/user-attachments/assets/e96cb889-801a-48f4-b61a-f4125fbb9051)

**Comment by TCOTC** [comment]
`转换为`(turnInto) 的子菜单我搞不懂

**Comment by Vanessa219** [comment]
里面的 id 是块 id，菜单的我加了一个  menuId?: string,
