### ISSUE TITLE
一些交互问题反馈

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2065]
https://ld246.com/article/1622830084349

## TODO

* [ ] ctrl+p 可以显示文件路径，以便定位到文件夹
![image](https://user-images.githubusercontent.com/970828/120888843-231f1680-c62d-11eb-859d-4d6f33e7a8d1.png)

## 待定

* [ ] 还是光标位置的问题，如果将来前进后退只记录光标的位置，可能会出现这种情况：在 A 文档开头编辑，滚动到 A 文档末尾，点击链接进入 B 文档，后退却会回到 A 文档的开头
* [ ] 前进后退、撤销、zoom out 等操作都涉及页面的变化，在每一个动作上可能都要单独考虑这里到底是要恢复光标位置还是恢复页面滚动位置（eg：第上面 10 条）

## v1.2.0 以后

* 页内搜索和替换 https://github.com/siyuan-note/insider/issues/441
  * [ ] 因为重构，页内搜索在这个版本暂时没了，但以前的页内搜索存在一个问题：不停地搜索下一个，定位到自己想要的位置之后，按 ESC 会跳回最后一次光标编辑的位置
  * [ ] 页内搜索的第二个问题：老版本无法在页内搜索锚文本，对 moc 页面很不方便

## 暂不考虑

* [ ] 反链面板可以增加解链操作 https://github.com/siyuan-note/siyuan/issues/590

## Done

* [x] 这张图里的上下文显示是不正常的，可能是因为关键词在段落的末尾：https://b3logfile.com/file/2021/06/image-d8262daa.png
* [x] 反链显示上下文的计算规则可能需要改进，因为显示反链上下文的时候锚文本往往并没有位于中心，导致一些完整句子被截断
* [x] 一个列表块如果折叠了，就不能使用上下移动的快捷键
* [x] 反链面板布局改进
* [x] 升级之后，顶部 tab 栏的右键菜单移除了很多选项，建议和文件树统一一下，菜单长一点无所谓，这个地方做减法会让使用过程不顺畅 https://github.com/siyuan-note/insider/issues/733
* [x] 现在点击附件链接会打开文件管理器（应该像以前一样直接打开该文件）
* [x] 新编辑器落地之后，可以考虑用 `C-v` 快捷键直接在正文里粘贴附件了（拖动方式添加附件很麻烦）
* [x] 文档树还是缺少一个收起全部的按钮，我自己很长一段时间里都用刷新代替，但是现在文件数目越来越多，刷新有点顶不住了
* [x] 确认窗口全都不能回车确认，需要光标点击确认键
* [x] 我只有一个笔记本，但很多人应该是多笔记本，在新建文档、移动文档的界面显示一下笔记本名会比较好
* [x] 还是光标位置的问题，进行撤销操作的时候，页面没有滚动到光标位置。比如在页面开头进行了编辑，然后滚动到页面底部按下撤销快捷键，因为页面没有随着撤销操作滚回页面开头，用户就看不到任何变化。

**Comment by 88250** [comment]
应该改的差不多了，没有改的后面单独开 issue。
