### ISSUE TITLE
Input method problem

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4826]
- [ ] QQ 拼音输入法候选栏未确认问题 https://ld246.com/article/165196354320
- [ ] 使用小狼毫输入法在图片后无法输入内容 https://ld246.com/article/1665719293692
- [ ] QQ 拼音开启匹配后无法引用 https://ld246.com/article/1676533354518
- [ ] 思源表格与 RIME 系列输入法的兼容性问题 https://ld246.com/article/1770045419150
- [ ] https://github.com/siyuan-note/siyuan/issues/9591
- [ ] https://github.com/siyuan-note/insider/issues/1123
- [ ] 有的输入法符号无法补全
- [ ] https://github.com/siyuan-note/siyuan/issues/14751
- [ ] https://github.com/siyuan-note/siyuan/issues/15461
- [ ] https://github.com/siyuan-note/siyuan/issues/14853
- [ ] https://github.com/siyuan-note/siyuan/issues/16270
- [ ] https://github.com/siyuan-note/siyuan/issues/15007
- [ ] https://github.com/siyuan-note/siyuan/issues/16317
- [ ] https://github.com/siyuan-note/siyuan/issues/16977
- [ ] https://github.com/siyuan-note/siyuan/issues/18074

已经无法重现：

- [x] https://github.com/siyuan-note/siyuan/issues/12065
- [x] 搜狗拼音快速改变标题后在下方输入中文丢失光标 https://ld246.com/article/1670146058185
- [x] https://github.com/siyuan-note/siyuan/issues/12496
- [x] https://github.com/siyuan-note/siyuan/issues/13290

**Comment by red-co** [comment]
Gboard cound't delete list-item node,
https://github.com/siyuan-note/siyuan/assets/75922982/82f0414b-2b42-4e8b-8dd3-ac9795cb9dbf

**Comment by red-co** [comment]
https://github.com/siyuan-note/siyuan/assets/75922982/82f0414b-2b42-4e8b-8dd3-ac9795cb9dbf

**Comment by TCOTC** [comment]
- [ ] #12496

**Comment by TCOTC** [comment]
https://ld246.com/article/1749268052078

**Comment by TCOTC** [comment]
https://ld246.com/article/1770045419150

**Comment by Vanessa219** [comment]
# 输入法问题优先级与合并清单

## P1：优先处理

以下按建议处理顺序排列，均未确认修复。

- [x] **行内公式相关的输入失焦与中文输入失效**：先处理公式开头段落全选后整个文档中文输入失效，再回归公式后继续输入时失焦；覆盖微软拼音、小狼毫
    - [x] [#18074：公式开头段落全选后中文输入失效](https://github.com/siyuan-note/siyuan/issues/18074)
    - [x] [#16977：行内公式后候选框不出现、光标丢失](https://github.com/siyuan-note/siyuan/issues/16977)
- [x] **表格内取消输入导致光标跳转或失焦**：合并处理 [#16317](https://github.com/siyuan-note/siyuan/issues/16317)（无法重现）、[2025 年小狼毫反馈](https://ld246.com/article/1749268052078)（无法重现）、[2026 年 RIME 反馈](https://ld246.com/article/1770045419150)（无法重现）；覆盖微软拼音、小狼毫、鼠须管，以及空表格、有内容表格；社区脚本有软换行副作用，不能视为完整修复
- [x] **特定输入法无法正常输入或组合文字**：分别保留各平台复现用例
    - [x] [#16270：Android 同文输入法在空文档无法输入](https://github.com/siyuan-note/siyuan/issues/16270)（无法重现）
    - [x] [#15461：Linux IBus 候选栏被打断、无法上屏](https://github.com/siyuan-note/siyuan/issues/15461)（没有环境无法调试，后续也没有类似反馈，暂时认为已经解决）
    - [x] [#9591：macOS 韩文字母无法正常组合](https://github.com/siyuan-note/siyuan/issues/9591) 无法重现
- [x] **[小狼毫在图片后无法继续输入](https://ld246.com/article/1665719293692)**（无法重现）：覆盖插入图片、粘贴图片、新段落和已有内容段落

## P2：后续处理

- [x] **块引用创建及后续输入异常**：按触发引用、新建文档、引用后继续输入三个阶段组织测试；以下均未确认修复
    - [x] [#14853：RIME 新输入的文字进入引用锚文本](https://github.com/siyuan-note/siyuan/issues/14853)
    - [x] [insider#1123：微信双拼通过引用新建文档后标点和光标错位](https://github.com/siyuan-note/insider/issues/1123)
    - [x] [QQ 拼音开启括号匹配后引用失效](https://ld246.com/article/1676533354518)
- [x] **输入法模式、快捷键与编辑器交互异常**：以下均未确认修复，保留两个独立用例
    - [x] [#14751：微软拼音兼容模式下显示异常](https://github.com/siyuan-note/siyuan/issues/14751)（无法重现）；关闭兼容模式只是绕过办法
    - [x] [#15007：macOS 使用快捷键后残留数字](https://github.com/siyuan-note/siyuan/issues/15007)：目前修改为 ⌃+1，已没有问题
- [x] **[#12496：iOS 收起搜狗键盘后编辑区域未恢复](https://github.com/siyuan-note/siyuan/issues/12496)**：待原环境回测；已有测试环境与报告者环境不同，尚不能确认修复，建议从“已经无法重现”中单独列出： 目前已无此交互

**Comment by 88250** [comment]
v3.8.4 已经解决所有已经发现的问题，关闭这个汇总了。
